[opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=50000
opcache.max_wasted_percentage=5
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.save_comments=1

; JIT для PHP 8.4
; tracing JIT — лучше для веб-приложений (1255 = CRTO: CPU, tracing, optimize all)
opcache.jit=tracing
opcache.jit_buffer_size=256M
