filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - drop_event:
      when:
        not:
          contains:
            container.name: "nginx-unit"

  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

output.elasticsearch:
  hosts: ["opensearch:9200"]
  index: "laravel-logs-%{+yyyy.MM.dd}"
  allow_older_versions: true  # отключает проверку версии и лицензии

setup.ilm.enabled: false
setup.template.name: "laravel-logs"
setup.template.pattern: "laravel-logs-*"