apiVersion: 1

datasources:

  # --- Jaeger (traces) ---
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    jsonData:
      tracesToLogsV2:
        datasourceUid: opensearch
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: "trace_id:${__span.traceId}"

  # --- OpenSearch (единый логовый источник) ---
  - name: OpenSearch Logs
    type: grafana-opensearch-datasource
    uid: opensearch
    access: proxy
    url: http://opensearch:9200
    jsonData:
      database: "logs-*"
      flavor: opensearch
      version: "2.19.1"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
      pplEnabled: true

  # --- Prometheus ---
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"