apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram-receiver
        type: telegram
        settings:
          bottoken: "8610586466:AAH2MljQzhjqLqekeho9I-pJTJfRsXn3RAg"
          chatid: "706579818"